.PHONY: install first-run run

install:
	@echo "[INFO] - - -> Instalando o projeto..."     \
	&& cd ./ProTecHub/                                \
	&& pip install poetry                             \
	&& poetry install   
	                              
.first-run:
	@echo "[INFO] - - -> Iniciando o projeto..."      \
	&& cd ./ProTecHub/                                \
	&& poetry run python manage.py makemigrations app \
	&& poetry run python manage.py migrate            \
	&& poetry run python manage.py runserver          

run:
	@echo "[INFO] - - -> Iniciando o projeto..."      \
	&& cd ./ProTecHub/                                \
	&& poetry run python manage.py runserver 
