# Generated by Django 5.1.1 on 2024-09-14 16:42

import app.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('validade', models.DateTimeField(default=datetime.datetime.now)),
                ('categoria', models.CharField(choices=[('Categoria I', 'I'), ('Categoria II', 'II'), ('Categoria III', 'III')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('Colaborador', 'Colaborador')], max_length=60)),
                ('cargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Pedreiro', 'Pedreiro')], max_length=60)),
                ('data_admissao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=datetime.datetime.now)),
                ('data_devolucao', models.DateTimeField(default=app.models.devolucao_padrao)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
